Tokenizer:
    type: "Byte-Pair Encoding"
    savepath: "Preprocess"
    corpus_path: "corpus.txt"
    vocab_size: 24_000

Model:
    embed_dim: 768   
    num_heads: 12     
    max_seq_len: 768 
    num_layers: 12
    stride_coeff: 2
    learning_rate : 1e-3
    dropout: 0.1
    rope_base: 10_000
    savepath: "Model\\Nova_best_model.safetensors"

    top_k : 5
    temperature : 0.5

Train:
    epochs: 1
    batch_size: 8

Datasets:
    SimpleStories_train : "Preprocess\\Datasets\\Vocab_train.pkl"
    SimpleStories_test : "Preprocess\\Datasets\\Vocab_test.pkl"

    Mixed_knowledge_train : "Preprocess\\Datasets\\Mixed_knowledge_train.pkl"
    Mixed_knowledge_test : "Preprocess\\Datasets\\Mixed_knowledge_test.pkl"

    Chat_train: "Preprocess\\Datasets\\chat_train.jsonl"
    Chat_test: "Preprocess\\Datasets\\chat_test.jsonl"

Metrics:
    savepath: "Model\\Metrics"
