Tokenizer:
    type: "Byte-Pair Encoding"
    savepath: "Preprocess"
    corpus_path: "corpus.txt"
    vocab_size: 10_000

Model:
    embed_dim: 768   
    num_heads: 8     
    max_seq_len: 768 
    num_layers: 6
    stride_coeff: 2
    learning_rate : 1e-4
    dropout: 0.1
    rope_base: 10_000
    savepath: "Model\\Nova_best_model.pth"

    top_k : 10
    temperature : 0.2

Train:
    epochs: 10
    batch_size: 8

Datasets:
    SimpleStories_train : "Preprocess\\Datasets\\Vocab_train.pkl"
    SimpleStories_test : "Preprocess\\Datasets\\Vocab_test.pkl"

    Mixed_knowledge_train : "Preprocess\\Datasets\\Mixed_knowledge_train.pkl"
    Mixed_knowledge_test : "Preprocess\\Datasets\\Mixed_knowledge_test.pkl"

    UltraChat_train: "Preprocess\\Datasets\\UltraChat_train.pkl"
    UltraChat_test: "Preprocess\\Datasets\\UltraChat_test.pkl"

Metrics:
    savepath: "Model\\Metrics"
